### ISSUE TITLE
Javascript error occured in the main process

### ISSUE THREAD

**Issue by jwdoom** [kyleady/TPlanet#7]
I got this error at first launch

Uncaught Exception:
ReferenceError: app is not defined
    at Object.<anonymous> (/private/var/folders/sl/w89rqxg109v8mj3k9v07904r0000gn/T/AppTranslocation/AC7260C3-C901-42BA-A7C7-1CC5AAE260E4/d/tplanet.app/Contents/Resources/app/mainMenu.js:149:12)
    at Object.<anonymous> (/private/var/folders/sl/w89rqxg109v8mj3k9v07904r0000gn/T/AppTranslocation/AC7260C3-C901-42BA-A7C7-1CC5AAE260E4/d/tplanet.app/Contents/Resources/app/mainMenu.js:227:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/folders/sl/w89rqxg109v8mj3k9v07904r0000gn/T/AppTranslocation/AC7260C3-C901-42BA-A7C7-1CC5AAE260E4/d/tplanet.app/Contents/Resources/app/main.js:55:1)

I got this after trying to open planet.exe

An error ocurred while saving to preferences.json: EROFS: read-only file system, open '/private/var/folders/sl/w89rqxg109v8mj3k9v07904r0000gn/T/AppTranslocation/AC7260C3-C901-42BA-A7C7-1CC5AAE260E4/d/tplanet.app/Contents/Resources/app/windows/index/preferences.json'

then this...

Error: Command failed: ./planet -s 0.032681318916703894 -h 150 -w 200 -m 1.0 -o GUIplanet.bmp -l 0.0 -L 0.0 -g 0.0 -G 0.0 -i -0.02 -C custom.col -a 0.0 -A 0.0 -V 0.035 -v -0.45 -T 0.0 0.0 -p m
/bin/sh: ./planet: No such file or directory

The app runs, but in front of the main window I get another blank window that says "tplanet" at the top bar.

I'm on a Mac Mini running 10.13.3. My Java Control Panels says I have the most recent version, 8 update 161.

**Comment by howdoicomputer** [comment]
@jwdoom `planet.exe` is a Windows executable so it won't run on anything but Windows. If you want a `planet` executable then you will have to compile it for your platform.

I run Linux and the author of this app runs Windows and Linux; this app generally isn't tested on macOS. I'd have to boot into a rarely used Mac partition to verify this but you could very well compile Planet Generator for macOS.

Something like:

```
brew install gcc
mkdir planet_build
cd planet_build
wget http://www.diku.dk/~torbenm/Planet/planet.zip
unzip planet.zip
make
mv planet <TPlanet directory>
```

If you're missing wget, unzip, make or whatever then you can use Homebrew to install that dependency. If you continue getting errors then we can investigate further but this might be a good start.

**Comment by kyleady** [comment]
Let me know if you have any further issues.

**Comment by jwdoom** [comment]
I don't know what any of that means. 

Weird thing is the installer did make a .app file that runs, it just doesn't work fully.

I'll stick a flag on this email and keep it in mind. Thanks for the information.
